server:
  port: 8080
config:
  openexchangerates:
    url: https://openexchangerates.org/api/
    token: 881e32c5642d4a39b15108085ac95384
  base-currency: USD
  gifs:
    up-trend: rich
    down-trend: broke
    flat-trend: nothing
  giphy:
    url: https://api.giphy.com/v1/gifs/random
    token: XUrURwQTrKhDSpEb6ZcYSL8HyIUGGMct
    rating: g
    resource: https://
logging:
  file:
    path: logs/dev_app.log
    max-size: 10MB
    max-history: 7
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    ru.vapima.currency  : TRACE

